import type { Chord } from "../types/ChordSet";

export const chords: Chord[] = [
  {
    name: "1",
    symbol: "I",
    triadNotes: [0, 2, 4],
    root: 0,
    chordFamily: "1",
    nextChordPossibilities: [
      { name: "1-7-42", weight: 6 },
      { name: "5-7-43", weight: 8 },
      { name: "5-7-65", weight: 8 },
      { name: "5/2-6", weight: 8 },
      { name: "1", weight: 10 },
      { name: "2", weight: 12 },
      { name: "3", weight: 1 },
      { name: "4", weight: 28 },
      { name: "5", weight: 41 },
      { name: "6", weight: 9 },
      { name: "7", weight: 6 },
      { name: "5/5", weight: 10 },
      { name: "5/5-6", weight: 6 },
      { name: "5/6", weight: 10 },
      { name: "5/2", weight: 10 },
      { name: "m4", weight: 10 },
      { name: "1-7", weight: 10 },
      { name: "2-6", weight: 10 },
      { name: "4-64", weight: 30 },
      { name: "6-6", weight: 15 },
      { name: "5-7", weight: 10 },
      // Bass-variety additions: I→V⁶ creates stepwise bass C-B (and resolves
      // back to C via V⁶→I), one of Bach's signature patterns.
      { name: "5-6", weight: 14 },
      { name: "1-6", weight: 8 },
    ],
    type: "tonic",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "2",
    root: 1,
    symbol: "ii",
    chordFamily: "2",
    triadNotes: [1, 3, 5],
    nextChordPossibilities: [
      { name: "5-7-65", weight: 10 },
      { name: "2", weight: 10 },
      { name: "5", weight: 70 },
      { name: "5-64", weight: 20 },
      { name: "5-7", weight: 10 },
      { name: "1-64", weight: 10 },
      { name: "7", weight: 10 },
    ],
    sharpScaleDegree: undefined,
    type: "predominant",
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "3",
    symbol: "iii",
    root: 2,
    chordFamily: "3",
    triadNotes: [2, 4, 6],
    nextChordPossibilities: [
      { name: "4", weight: 53 },
      { name: "5", weight: 6 },
      { name: "6", weight: 32 },
      { name: "4-6", weight: 15 },
      { name: "6-6", weight: 15 },
      { name: "5-6", weight: 15 },
      { name: "5/5-6", weight: 12 },
    ],
    type: "mediant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "4",
    symbol: "IV",
    root: 3,
    chordFamily: "4",
    triadNotes: [3, 5, 0],
    nextChordPossibilities: [
      { name: "5-7-42", weight: 8 },
      { name: "5-7-43", weight: 8 },
      { name: "1", weight: 22 },
      { name: "2", weight: 13 },
      { name: "5", weight: 39 },
      { name: "7", weight: 15 },
      // IV→I⁶ creates stepwise descending bass F→E (or I⁶→ii: E→D after).
      { name: "1-6", weight: 12 },
      { name: "5-6", weight: 8 },
    ],
    type: "predominant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "5",
    symbol: "V",
    root: 4,
    chordFamily: "5",
    triadNotes: [4, 6, 1],
    nextChordPossibilities: [
      { name: "5/6-6", weight: 8 },
      { name: "1", weight: 83 },
      { name: "5", weight: 17 },
      { name: "6", weight: 17 },
      { name: "5/5", weight: 10 },
      { name: "5/5-6", weight: 6 },
      { name: "5/6", weight: 10 },
      // Rare-but-allowable when soprano steps to a degree none of 1/5/6
      // cover (e.g. F in C major needs degree 3, only in IV/ii/I⁶).
      { name: "4", weight: 3 },
      { name: "2", weight: 3 },
      { name: "1-6", weight: 3 },
    ],
    type: "dominant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "6",
    symbol: "vi",
    root: 5,
    chordFamily: "6",
    triadNotes: [5, 0, 2],
    nextChordPossibilities: [
      { name: "5-7-42", weight: 6 },
      { name: "1", weight: 12 },
      { name: "2", weight: 30 },
      { name: "3", weight: 8 },
      { name: "4", weight: 7 },
      { name: "7", weight: 9 },
      { name: "5/5", weight: 10 },
      { name: "5/5-6", weight: 6 },
      { name: "5/6", weight: 15 },
    ],
    type: "mediant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "7",
    symbol: "vii°",
    root: 6,
    chordFamily: "7",
    triadNotes: [6, 1, 3],
    nextChordPossibilities: [{ name: "1", weight: 100 }],
    type: "leading-tone",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "5-7",
    symbol: "V⁷",
    root: 4,
    chordFamily: "5-7",
    triadNotes: [4, 6, 1, 3],
    nextChordPossibilities: [
      { name: "1", weight: 100 },
      { name: "6", weight: 8 },
      { name: "1-6", weight: 4 },
    ],
    type: "dominant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "5/5",
    symbol: "V/V",
    root: 1,
    chordFamily: "5/5",
    triadNotes: [1, 3, 5],
    nextChordPossibilities: [
      { name: "5", weight: 70 },
      { name: "5-6", weight: 15 },
      { name: "5-64", weight: 15 },
    ],
    type: "secondary-dominant",
    sharpScaleDegree: 3,
    flatScaleDegree: undefined,
    baseMultiplier: 10,
  },
  {
    // V⁶/V: first inversion of V/V — chromatic 3rd (F# in C major) is in the bass.
    // Only valid when the preceding bass note is a diatonic step away from the chromatic degree.
    // Resolves: F#(3) → G(4) by step upward.
    name: "5/5-6",
    symbol: "V⁶/V",
    root: 3,             // degree 3 (chromatically raised) is in the bass
    chordFamily: "5/5",
    triadNotes: [1, 3, 5],
    nextChordPossibilities: [
      { name: "5", weight: 70 },     // V (G bass) — F# resolves up to G by step
      // I⁶₄ (G bass) — the same step resolution, and then the cadential
      // six-four falls to V. Correct, and deliberately the rarer path.
      { name: "1-64", weight: 30 },
    ],
    type: "secondary-dominant",
    sharpScaleDegree: 3,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "5/6",
    symbol: "V/vi",
    root: 2,
    chordFamily: "5/6",
    triadNotes: [2, 4, 6],
    nextChordPossibilities: [
      // A secondary dominant resolves to its target in root position. At 50/50
      // this landed on vi⁶ half the time, which is a weak arrival and leaves
      // the bass to jump away from a leading tone it should have stepped off.
      { name: "6", weight: 85 },
      { name: "6-6", weight: 15 },
    ],
    type: "secondary-dominant",
    sharpScaleDegree: 4,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "5/2",
    symbol: "V/ii",
    root: 5,
    chordFamily: "5/2",
    triadNotes: [5, 0, 2],
    nextChordPossibilities: [
      { name: "2", weight: 85 },
      { name: "2-6", weight: 15 },
    ],
    type: "secondary-dominant",
    sharpScaleDegree: 0,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    // V⁶/vi: first inversion of V/vi, so the chromatic 3rd (G# in C major) is
    // the bass note rather than an inner voice. Approached by step from G or A
    // and resolved G# → A, both enforced because chord.root === sharpScaleDegree.
    //
    // Without this the chromatic note could only reach the bass through the
    // deadlock escape in build-chord-notes, which owes it no resolution - it
    // arrived by accident and wandered off.
    name: "5/6-6",
    symbol: "V⁶/vi",
    root: 4,
    chordFamily: "5/6",
    triadNotes: [2, 4, 6],
    nextChordPossibilities: [
      // V⁶/vi puts the leading tone of vi in the bass, and it has to rise a
      // step onto vi's root. vi⁶ puts a different note there, so the
      // resolution never happens and the bass leaps away instead.
      { name: "6", weight: 100 },
    ],
    type: "secondary-dominant",
    sharpScaleDegree: 4,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    // V⁶/ii: the same idea a step lower. C# in the bass, approached from C or D,
    // resolving C# → D.
    name: "5/2-6",
    symbol: "V⁶/ii",
    root: 0,
    chordFamily: "5/2",
    triadNotes: [5, 0, 2],
    nextChordPossibilities: [
      // Same as V⁶/vi: the bass is ii's leading tone and must step up to it.
      { name: "2", weight: 100 },
    ],
    type: "secondary-dominant",
    sharpScaleDegree: 0,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    // V6/5. The leading tone is in the bass and must rise, so this can only go
    // to I in root position - which is what the entry for `1` gives when the
    // resolution is owed.
    name: "5-7-65",
    symbol: "V⁶₅",
    root: 6,
    chordFamily: "5-7",
    triadNotes: [4, 6, 1, 3],
    nextChordPossibilities: [{ name: "1", weight: 100 }],
    type: "dominant-inversion",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    // V4/3. The 5th is in the bass and is free, so either inversion of I works.
    name: "5-7-43",
    symbol: "V⁴₃",
    root: 1,
    chordFamily: "5-7",
    triadNotes: [4, 6, 1, 3],
    nextChordPossibilities: [
      { name: "1", weight: 60 },
      { name: "1-6", weight: 40 },
    ],
    type: "dominant-inversion",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    // V4/2. The seventh is in the bass and a seventh falls, so this resolves to
    // I6 and to nothing else - the case that started this: a bass note whose
    // inversion determines the only chord that can follow it.
    name: "5-7-42",
    symbol: "V⁴₂",
    root: 3,
    chordFamily: "5-7",
    triadNotes: [4, 6, 1, 3],
    nextChordPossibilities: [{ name: "1-6", weight: 100 }],
    type: "dominant-inversion",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    // V4/2 of IV: the flattened seventh (Bb in C) is in the bass and falls a
    // step to A, so IV6 is the only resolution.
    name: "1-7-42",
    symbol: "V⁴₂/IV",
    root: 6,
    chordFamily: "1-7",
    triadNotes: [0, 2, 4, 6],
    nextChordPossibilities: [{ name: "4-6", weight: 100 }],
    type: "secondary-dominant",
    sharpScaleDegree: undefined,
    flatScaleDegree: 6,
    baseMultiplier: 1,
  },
  {
    // iv6: the flattened 6th (Ab in C) sits in the bass and falls to G. The only
    // borrowed chord that puts a lowered degree in the bass.
    name: "m4-6",
    symbol: "iv⁶",
    root: 5,
    chordFamily: "m4",
    triadNotes: [3, 5, 0],
    nextChordPossibilities: [
      { name: "5", weight: 60 },
      { name: "5-7", weight: 40 },
    ],
    type: "predominant",
    sharpScaleDegree: undefined,
    flatScaleDegree: 5,
    baseMultiplier: 1,
  },
  {
    name: "m4",
    symbol: "iv",
    root: 3,
    chordFamily: "m4",
    triadNotes: [3, 5, 0],
    nextChordPossibilities: [
      { name: "1", weight: 30 },
      { name: "1-6", weight: 30 },
      { name: "1-64", weight: 30 },
    ],
    type: "plagal",
    sharpScaleDegree: undefined,
    flatScaleDegree: 5,
    baseMultiplier: 1,
  },
  {
    name: "1-7",
    symbol: "V⁷/IV",
    root: 0,
    chordFamily: "1-7",
    // C E G Bb. The root was missing from this list, unlike every other seventh
    // chord (V7 is [4,6,1,3]), which left the chord three notes and put its
    // flattened 7th out of reach of the bass entirely.
    triadNotes: [0, 2, 4, 6],
    nextChordPossibilities: [
      { name: "4", weight: 100 },
      // A pedal six-four: the bass holds C while the seventh falls Bb->A.
      // Genuine, but an idiom rather than the ordinary resolution - weighted
      // level with IV it was turning up about half the time.
      { name: "4-64", weight: 25 },
    ],
    type: "secondary-dominant",
    sharpScaleDegree: undefined,
    flatScaleDegree: 6,
    baseMultiplier: 1,
  },
  {
    name: "1-64",
    symbol: "I⁶₄",
    root: 4,
    chordFamily: "1",
    triadNotes: [0, 2, 4],
    nextChordPossibilities: [
      { name: "5/6-6", weight: 10 },
      { name: "5", weight: 100 },
      { name: "5/5-6", weight: 15 },
    ],
    type: "predominant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "5-64",
    symbol: "V⁶₄",
    root: 1,
    chordFamily: "5",
    triadNotes: [4, 6, 1],
    nextChordPossibilities: [
      { name: "1", weight: 100 },
      { name: "3", weight: 50 },
      { name: "5-6", weight: 50 },
    ],
    type: "dominant-inversion",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "2-6",
    symbol: "ii⁶",
    root: 3,
    chordFamily: "2",
    triadNotes: [1, 3, 5],
    nextChordPossibilities: [
      { name: "1", weight: 22 },
      { name: "2", weight: 13 },
      { name: "5", weight: 39 },
      { name: "7", weight: 23 },
    ],
    type: "predominant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "4-6",
    symbol: "IV⁶",
    root: 5,
    chordFamily: "4",
    triadNotes: [3, 5, 0],
    nextChordPossibilities: [
      { name: "m4-6", weight: 6 },
      { name: "5/6-6", weight: 10 },
      { name: "1", weight: 15 },
      { name: "5", weight: 30 },
      { name: "5-6", weight: 20 },
      { name: "5-64", weight: 40 },
      { name: "5-7", weight: 10 },
      { name: "1-64", weight: 30 },
      { name: "2", weight: 40 },
      { name: "2-6", weight: 20 },
    ],
    type: "predominant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "4-64",
    symbol: "IV⁶₄",
    root: 0,
    chordFamily: "4",
    triadNotes: [3, 5, 0],
    nextChordPossibilities: [
      { name: "5/2-6", weight: 10 },
      { name: "1", weight: 100 },
      { name: "5-64", weight: 50 },
    ],
    type: "predominant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "6-6",
    symbol: "vi⁶",
    root: 0,
    chordFamily: "6",
    triadNotes: [5, 0, 2],
    nextChordPossibilities: [
      { name: "5/2-6", weight: 8 },
      { name: "1", weight: 12 },
      { name: "2", weight: 30 },
      { name: "3", weight: 8 },
      { name: "4", weight: 7 },
      { name: "7", weight: 9 },
      { name: "5-6", weight: 10 },
    ],
    type: "mediant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "5-6",
    symbol: "V⁶",
    root: 6,
    chordFamily: "5",
    triadNotes: [4, 6, 1],
    nextChordPossibilities: [
      { name: "1", weight: 100 },
      { name: "6", weight: 6 },
      { name: "1-6", weight: 3 },
    ],
    type: "dominant-inversion",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "1-6",
    symbol: "I⁶",
    root: 2,
    chordFamily: "1",
    triadNotes: [0, 2, 4],
    nextChordPossibilities: [
      { name: "m4-6", weight: 8 },
      { name: "1", weight: 10 },
      { name: "4", weight: 50 },
      { name: "6", weight: 9 },
      { name: "5/5-6", weight: 18 },
      { name: "5/6", weight: 10 },
      { name: "5/2", weight: 10 },
      { name: "m4", weight: 10 },
      { name: "2-6", weight: 20 },
      { name: "6-6", weight: 15 },
    ],
    type: "tonic-inversion",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },

  // ── Minor mode chords ────────────────────────────────────────────────────────
  // Scale degrees are key-relative (0=tonic). The diatonic scale of the minor
  // key automatically produces the correct chord quality (minor/major/dim) from
  // triadNotes alone. Only the harmonic dominant V and vii° need sharpScaleDegree:6
  // to raise the 7th scale degree (subtonic → leading tone).

  {
    name: "m_i",
    symbol: "i",
    mode: "minor",
    root: 0,
    triadNotes: [0, 2, 4],
    nextChordPossibilities: [
      { name: "m_iv", weight: 30 },
      { name: "m_V", weight: 35 },
      { name: "m_VI", weight: 15 },
      { name: "m_VII", weight: 10 },
      { name: "m_iid", weight: 8 },
      { name: "m_III", weight: 5 },
      { name: "m_i6", weight: 5 },
    ],
    type: "tonic",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "m_i6",
    symbol: "i⁶",
    mode: "minor",
    root: 2,
    triadNotes: [0, 2, 4],
    nextChordPossibilities: [
      { name: "m_iv", weight: 30 },
      { name: "m_V", weight: 30 },
      { name: "m_iid", weight: 20 },
      { name: "m_i", weight: 10 },
      { name: "m_VI", weight: 10 },
    ],
    type: "tonic-inversion",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    // Minor cadential 6/4: i in 2nd inversion (5th of i in the bass = degree 4),
    // routed at cadences as iv → i⁶₄ → V → i. Same diatonic notes as i but the
    // bass walks 4 → 4 → 4 → 0 (G→G→G→C in Cm: the bass holds the V's root).
    name: "m_i64",
    symbol: "i⁶₄",
    mode: "minor",
    root: 4,
    triadNotes: [0, 2, 4],
    nextChordPossibilities: [
      { name: "m_V", weight: 100 },
    ],
    type: "predominant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "m_iv",
    symbol: "iv",
    mode: "minor",
    root: 3,
    triadNotes: [3, 5, 0],
    nextChordPossibilities: [
      { name: "m_V", weight: 55 },
      { name: "m_i", weight: 20 },
      { name: "m_iid", weight: 15 },
      { name: "m_VII", weight: 10 },
      { name: "m_i64", weight: 10 }, // cadential 6/4 ornament
    ],
    type: "predominant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "m_iid",
    symbol: "ii°",
    mode: "minor",
    root: 1,
    triadNotes: [1, 3, 5],
    nextChordPossibilities: [
      { name: "m_V", weight: 80 },
      { name: "m_i", weight: 20 },
    ],
    type: "predominant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    // Harmonic dominant — sharpScaleDegree:6 raises the 7th (subtonic→leading tone)
    name: "m_V",
    symbol: "V",
    mode: "minor",
    root: 4,
    triadNotes: [4, 6, 1],
    nextChordPossibilities: [
      { name: "m_i", weight: 85 },
      { name: "m_VI", weight: 15 },
      // Rare but allowable Bach minor-mode transitions when soprano steps to
      // a note that none of i/VI cover (e.g. E→D needs degree 3, only in iv/ii°).
      { name: "m_iv", weight: 4 },
      { name: "m_iid", weight: 3 },
      { name: "m_i6", weight: 3 },
    ],
    type: "dominant",
    sharpScaleDegree: 6,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "m_V7",
    symbol: "V⁷",
    mode: "minor",
    root: 4,
    triadNotes: [4, 6, 1, 3],
    nextChordPossibilities: [
      { name: "m_i", weight: 100 },
      { name: "m_VI", weight: 8 },
      { name: "m_i6", weight: 4 },
    ],
    type: "dominant",
    sharpScaleDegree: 6,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "m_VI",
    symbol: "VI",
    mode: "minor",
    root: 5,
    triadNotes: [5, 0, 2],
    nextChordPossibilities: [
      { name: "m_iv", weight: 35 },
      { name: "m_iid", weight: 25 },
      { name: "m_VII", weight: 20 },
      { name: "m_V", weight: 15 },
      { name: "m_i", weight: 5 },
    ],
    type: "mediant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "m_VII",
    symbol: "VII",
    mode: "minor",
    root: 6,
    triadNotes: [6, 1, 3],
    nextChordPossibilities: [
      { name: "m_III", weight: 40 },
      { name: "m_i", weight: 30 },
      { name: "m_V", weight: 20 },
      { name: "m_VI", weight: 10 },
    ],
    type: "subtonic",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    name: "m_III",
    symbol: "III",
    mode: "minor",
    root: 2,
    triadNotes: [2, 4, 6],
    nextChordPossibilities: [
      { name: "m_VI", weight: 40 },
      { name: "m_iv", weight: 25 },
      { name: "m_VII", weight: 20 },
      { name: "m_V", weight: 15 },
    ],
    type: "mediant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  {
    // Leading-tone diminished — root is degree 6, raised to leading tone via sharpScaleDegree:6
    name: "m_viid",
    symbol: "vii°",
    mode: "minor",
    root: 6,
    triadNotes: [6, 1, 3],
    nextChordPossibilities: [
      { name: "m_i", weight: 100 },
      { name: "m_VI", weight: 8 },
      { name: "m_i6", weight: 4 },
    ],
    type: "leading-tone",
    sharpScaleDegree: 6,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
];
