import type { symbol } from "astro/zod";

export const chords: {
  [key: string]: {
    name: string;
    symbol: string;
    triadNotes: number[];
    root: number;
    chordFamily?: string;
    nextChordPossibilities: { name: string; weight: number }[];
    type: string;
    sharpScaleDegree: number | undefined;
    flatScaleDegree: number | undefined;
    baseMultiplier: number;
  };
} = {
  "1": {
    name: "1",
    symbol: "I",
    triadNotes: [0, 2, 4],
    root: 0,
    chordFamily: "1",
    nextChordPossibilities: [
      { name: "1", weight: 10 },
      { name: "2", weight: 12 },
      { name: "3", weight: 1 },
      { name: "4", weight: 28 },
      { name: "5", weight: 41 },
      { name: "6", weight: 9 },
      { name: "7", weight: 6 },
      { name: "5/5", weight: 10 },
      { name: "5/6", weight: 10 },
      { name: "5/2", weight: 10 },
      { name: "m4", weight: 10 },
      { name: "1-7", weight: 10 },
      { name: "2-6", weight: 10 },
      { name: "4-64", weight: 30 },
      { name: "6-6", weight: 15 },
      { name: "5-7", weight: 10 },
    ],
    type: "tonic",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  "2": {
    name: "2",
    root: 1,
    symbol: "ii",
    chordFamily: "2",
    triadNotes: [1, 3, 5],
    nextChordPossibilities: [
      { name: "2", weight: 10 },
      { name: "5", weight: 70 },
      { name: "5-64", weight: 20 },
      { name: "5-7", weight: 10 },
      { name: "1-64", weight: 10 },
      { name: "7", weight: 10 },
    ],
    sharpScaleDegree: undefined,
    type: "predominant",
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  "3": {
    name: "3",
    symbol: "iii",
    root: 2,
    chordFamily: "3",
    triadNotes: [2, 4, 6],
    nextChordPossibilities: [
      { name: "4", weight: 53 },
      { name: "5", weight: 6 },
      { name: "6", weight: 32 },
      { name: "4-6", weight: 15 },
      { name: "6-6", weight: 15 },
      { name: "5-6", weight: 15 },
    ],
    type: "mediant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  "4": {
    name: "4",
    symbol: "IV",
    root: 3,

    chordFamily: "4",
    triadNotes: [3, 5, 0],
    nextChordPossibilities: [
      { name: "1", weight: 22 }, // Adjust the weight as needed
      { name: "2", weight: 13 }, // Adjust the weight as needed
      { name: "5", weight: 39 },
      { name: "7", weight: 15 }, // Adjust the weight as needed
    ],
    type: "predominant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  "5": {
    name: "5",
    symbol: "V",
    root: 4,
    chordFamily: "5",
    triadNotes: [4, 6, 1],
    nextChordPossibilities: [
      { name: "1", weight: 83 },
      { name: "5", weight: 17 },
      { name: "6", weight: 17 },
      { name: "5/5", weight: 10 },
      { name: "5/6", weight: 10 },
    ],
    type: "dominant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  "6": {
    name: "6",
    symbol: "vi",
    root: 5,
    chordFamily: "6",
    triadNotes: [5, 0, 2],
    nextChordPossibilities: [
      { name: "1", weight: 12 },
      { name: "2", weight: 30 },
      { name: "3", weight: 8 },
      { name: "4", weight: 7 },
      { name: "7", weight: 9 },
      { name: "5/5", weight: 10 },
      { name: "5/6", weight: 15 },
    ],
    type: "mediant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  "7": {
    name: "7",
    symbol: "vii°",
    root: 6,
    chordFamily: "7",
    triadNotes: [6, 1, 3],
    nextChordPossibilities: [
      { name: "1", weight: 100 }, // Adjust the weight as needed
    ],
    type: "leading-tone",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  "5-7": {
    name: "5-7",
    symbol: "V⁷",
    root: 4,
    chordFamily: "5-7",
    triadNotes: [6, 1, 3],
    nextChordPossibilities: [{ name: "1", weight: 100 }],
    type: "dominant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  "5/5": {
    name: "5/5",
    symbol: "V/V",
    root: 1,
    chordFamily: "5/5",
    triadNotes: [1, 3, 5],
    nextChordPossibilities: [
      { name: "5", weight: 30 },
      { name: "5-6", weight: 30 },
      { name: "5-64", weight: 30 },
    ],
    type: "secondary-dominant",
    sharpScaleDegree: 3,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  "5/6": {
    name: "5/6",
    symbol: "V/vi",
    root: 2,
    chordFamily: "5/6",
    triadNotes: [2, 4, 6],
    nextChordPossibilities: [
      { name: "6", weight: 50 },
      { name: "6-6", weight: 50 },
    ],
    type: "secondary-dominant",
    sharpScaleDegree: 4,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  "5/2": {
    name: "5/2",
    symbol: "V/ii",
    root: 5,
    chordFamily: "5/2",
    triadNotes: [5, 0, 2],
    nextChordPossibilities: [
      { name: "2", weight: 50 },
      { name: "2-6", weight: 50 },
    ],
    type: "secondary-dominant",
    sharpScaleDegree: 0,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },

  m4: {
    name: "m4",
    symbol: "iv",
    root: 3,
    chordFamily: "m4",
    triadNotes: [3, 5, 0],
    nextChordPossibilities: [
      { name: "1", weight: 30 },
      { name: "1-6", weight: 30 },
      { name: "1-64", weight: 30 },
    ],
    type: "plagal",
    sharpScaleDegree: undefined,
    flatScaleDegree: 5,
    baseMultiplier: 1,
  },
  "1-7": {
    name: "1-7",
    symbol: "I⁷",
    root: 0,
    chordFamily: "1-7",
    triadNotes: [2, 4, 6],
    nextChordPossibilities: [
      { name: "4", weight: 100 },
      { name: "4-64", weight: 100 },
    ],
    type: "secondary-dominant",
    sharpScaleDegree: undefined,
    flatScaleDegree: 6,
    baseMultiplier: 1,
  },
  "1-64": {
    name: "1-64",
    symbol: "I⁶₄",
    root: 4,
    chordFamily: "1",
    triadNotes: [0, 2, 4],
    nextChordPossibilities: [{ name: "5", weight: 100 }],
    type: "predominant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  "5-64": {
    name: "5-64",
    symbol: "V⁶₄",
    root: 1,
    chordFamily: "5",
    triadNotes: [4, 6, 1],
    nextChordPossibilities: [
      { name: "1", weight: 100 },
      { name: "3", weight: 50 },
      { name: "5-6", weight: 50 },
    ],
    type: "dominant-inversion",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  "2-6": {
    name: "2-6",
    symbol: "ii⁶",
    root: 3,
    chordFamily: "2",
    triadNotes: [1, 3, 5],
    nextChordPossibilities: [
      { name: "1", weight: 22 }, // Adjust the weight as needed
      { name: "2", weight: 13 }, // Adjust the weight as needed
      { name: "5", weight: 39 },
      { name: "7", weight: 23 },
    ],
    type: "predominant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  "4-6": {
    name: "4-6",
    symbol: "IV⁶",
    root: 5,
    chordFamily: "4",
    triadNotes: [3, 5, 0],
    nextChordPossibilities: [
      { name: "1", weight: 15 },
      { name: "5", weight: 30 },
      { name: "5-6", weight: 20 },
      { name: "5-64", weight: 40 },
      { name: "5-7", weight: 10 },
      { name: "1-64", weight: 30 },
      { name: "2", weight: 40 },
      { name: "2-6", weight: 20 },
    ],
    type: "predominant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  "4-64": {
    name: "4-64",
    symbol: "IV⁶₄",
    root: 0,
    chordFamily: "4",
    triadNotes: [3, 5, 0],
    nextChordPossibilities: [
      { name: "1", weight: 100 },
      { name: "5-64", weight: 50 },
    ],
    type: "predominant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  "6-6": {
    name: "6-6",
    symbol: "vi⁶",
    root: 0,
    chordFamily: "6",
    triadNotes: [5, 0, 2],
    nextChordPossibilities: [
      { name: "1", weight: 12 },
      { name: "2", weight: 30 },
      { name: "3", weight: 8 },
      { name: "4", weight: 7 },
      { name: "7", weight: 9 },
      { name: "5-6", weight: 10 },
    ],
    type: "mediant",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  "5-6": {
    name: "5-6",
    symbol: "V⁶",
    root: 6,
    chordFamily: "5",
    triadNotes: [4, 6, 1],
    nextChordPossibilities: [{ name: "1", weight: 100 }],
    type: "dominant-inversion",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
  "1-6": {
    name: "1-6",
    symbol: "I⁶",
    root: 2,
    chordFamily: "1",
    triadNotes: [0, 2, 4],
    nextChordPossibilities: [
      { name: "1", weight: 10 },
      { name: "4", weight: 50 },
      { name: "6", weight: 9 },
      { name: "5/6", weight: 10 },
      { name: "5/2", weight: 10 },
      { name: "m4", weight: 10 },
      { name: "2-6", weight: 20 },
      { name: "6-6", weight: 15 },
    ],
    type: "tonic-inversion",
    sharpScaleDegree: undefined,
    flatScaleDegree: undefined,
    baseMultiplier: 1,
  },
};
