export interface Rhythm {
  name: string;
  abcValue: string[];
  meterValue: number[];
  totalValue: number;
  rest: boolean;
  chunk?: boolean;
  oddsWeight: number;
  maxRng: number;
  pattern?: boolean;
  png?: string;
}

export const rhythms = {
  thirtySecond: {
    name: "thirtySecond",
    abcValue: ["1"],
    meterValue: [1 / 32],
    totalValue: 1 / 32,
    rest: false,
    oddsWeight: 0,
    pattern: false,
    maxRng: 0,
  },
  thirtySecondRest: {
    name: "thirtySecondRest",
    abcValue: ["z1"],
    meterValue: [1 / 32],
    totalValue: 1 / 32,
    rest: true,
    oddsWeight: 0,
    pattern: false,
    maxRng: 0,
  },
  sixteenth: {
    name: "sixteenth",
    abcValue: ["2"],
    meterValue: [1 / 16],
    totalValue: 1 / 16,
    rest: false,
    oddsWeight: 10,
    maxRng: 0,
    pattern: false,
  },
  sixteenthRest: {
    name: "sixteenthRest",
    abcValue: ["z2"],
    meterValue: [1 / 16],
    totalValue: 1 / 16,
    rest: true,
    oddsWeight: 0,
    maxRng: 0,
    pattern: false,
  },
  dotSixteenth: {
    name: "dotSixteenth",
    abcValue: ["3"],
    meterValue: [3 / 32],
    totalValue: 3 / 32,
    rest: false,
    oddsWeight: 0,
    maxRng: 0,
    pattern: false,
  },
  dotSixteenthRest: {
    name: "dotSixteenthRest",
    abcValue: ["z3"],
    meterValue: [1 / 16],
    totalValue: 1 / 16,
    rest: true,
    oddsWeight: 0,
    maxRng: 0,
    pattern: false,
  },
  eighth: {
    name: "eighth",
    abcValue: ["4"],
    meterValue: [1 / 8],
    totalValue: 1 / 8,
    rest: false,
    oddsWeight: 10,
    maxRng: 0,
    pattern: false,
  },
  eighthRest: {
    name: "eighthRest",
    abcValue: ["z4"],
    meterValue: [1 / 8],
    totalValue: 1 / 8,
    rest: true,
    oddsWeight: 0,
    maxRng: 0,
    pattern: false,
  },
  dotEighth: {
    name: "dotEighth",
    abcValue: ["6"],
    meterValue: [3 / 16],
    totalValue: 3 / 16,
    rest: false,
    oddsWeight: 0,
    maxRng: 0,
    pattern: false,
  },
  dotEighthRest: {
    name: "dotEighthRest",
    abcValue: ["z6"],
    meterValue: [1 / 8],
    totalValue: 1 / 8,
    rest: true,
    oddsWeight: 0,
    maxRng: 0,
    pattern: false,
  },
  quarter: {
    name: "quarter",
    abcValue: ["8"],
    meterValue: [1 / 4],
    totalValue: 1 / 4,
    rest: false,
    oddsWeight: 10,
    maxRng: 0,
    pattern: false,
  },
  quarterRest: {
    name: "quarterRest",
    abcValue: ["z8"],
    meterValue: [1 / 4],
    totalValue: 1 / 4,
    rest: true,
    oddsWeight: 0,
    maxRng: 0,
    pattern: false,
  },
  dotQuarter: {
    name: "dotQuarter",
    abcValue: ["10"],
    meterValue: [3 / 8],
    totalValue: 3 / 8,
    rest: false,
    oddsWeight: 0,
    maxRng: 0,
    pattern: false,
  },
  dotQuarterRest: {
    name: "dotQuarterRest",
    abcValue: ["z10"],
    meterValue: [1 / 4],
    totalValue: 1 / 4,
    rest: true,
    oddsWeight: 0,
    maxRng: 0,
    pattern: false,
  },
  half: {
    name: "half",
    abcValue: ["16"],
    meterValue: [1 / 2],
    totalValue: 1 / 2,
    rest: false,
    oddsWeight: 10,
    maxRng: 0,
    pattern: false,
  },
  halfRest: {
    name: "halfRest",
    abcValue: ["z16"],
    meterValue: [1 / 2],
    totalValue: 1 / 2,
    rest: true,
    oddsWeight: 0,
    maxRng: 0,
    pattern: false,
  },
  dotHalf: {
    name: "dotHalf",
    abcValue: ["20"],
    meterValue: [3 / 4],
    totalValue: 3 / 4,
    rest: false,
    oddsWeight: 0,
    maxRng: 0,
    pattern: false,
  },
  dotHalfRest: {
    name: "dotHalfRest",
    abcValue: ["z20"],
    meterValue: [1 / 2],
    totalValue: 1 / 2,
    rest: true,
    oddsWeight: 0,
    maxRng: 0,
    pattern: false,
  },
  whole: {
    name: "whole",
    abcValue: ["32"],
    meterValue: [1],
    totalValue: 1,
    rest: false,
    oddsWeight: 10,
    maxRng: 0,
    pattern: false,
  },
  wholeRest: {
    name: "wholeRest",
    abcValue: ["z32"],
    meterValue: [1],
    totalValue: 1,
    rest: true,
    oddsWeight: 0,
    maxRng: 0,
    pattern: false,
  },
  fourEigths: {
    name: "fourEigths",
    abcValue: ["4", "4", "4", "4"],
    meterValue: [1 / 8, 1 / 8, 1 / 8, 1 / 8],
    totalValue: 1 / 2,
    rest: false,
    chunk: true,
    oddsWeight: 0,
    maxRng: 0,
    pattern: true,
  },
  fourSixteenths: {
    name: "fourSixteenths",
    abcValue: ["2", "2", "2", "2"],
    meterValue: [1 / 16, 1 / 16, 1 / 16, 1 / 16],
    totalValue: 1 / 4,
    rest: false,
    chunk: true,
    oddsWeight: 0,
    maxRng: 0,
    pattern: true,
  },
  eigthSixteenthSixteenth: {
    name: "eigthSixteenthSixteenth",
    abcValue: ["4", "2", "2"],
    meterValue: [1 / 8, 1 / 16, 1 / 16],
    totalValue: 1 / 4,
    rest: false,
    chunk: true,
    oddsWeight: 0,
    maxRng: 0,
    pattern: true,
  },
  sixteenthSixteenthEighth: {
    name: "sixteenthSixteenthEighth",
    abcValue: ["2", "2", "4"],
    meterValue: [1 / 16, 1 / 16, 1 / 8],
    totalValue: 1 / 4,
    rest: false,
    chunk: true,
    oddsWeight: 0,
    maxRng: 0,
    pattern: true,
  },
  dotEighthSixteenth: {
    name: "dotEighthSixteenth",
    abcValue: ["6", "2"],
    meterValue: [3 / 16, 1 / 16],
    totalValue: 1 / 4,
    rest: false,
    chunk: true,
    oddsWeight: 0,
    maxRng: 0,
    pattern: true,
  },
  dotQuarterEighth: {
    name: "dotQuarterEighth",
    abcValue: ["10", "4"],
    meterValue: [3 / 8, 1 / 8],
    totalValue: 1 / 2,
    rest: false,
    chunk: true,
    oddsWeight: 0,
    maxRng: 0,
    pattern: true,
  },
  dotHalfQuarter: {
    name: "dotHalfQuarter",
    abcValue: ["20", "8"],
    meterValue: [3 / 4, 1 / 4],
    totalValue: 1,
    rest: false,
    chunk: true,
    oddsWeight: 0,
    maxRng: 0,
    pattern: true,
  },

  // ... add other patterns
  // ... add other patterns
} as const;
