export interface Rhythm {
  weight: number;
  name: string;
  abcValue: string[];
  meterValue: number[];
  totalValue: number;
  singleNoteValue?: number; // Value of individual note in a pattern
  rest: boolean;
  oddsWeight: number;
  maxRng: number;
  pattern?: boolean;
  symbol: string;
  /**
   * The meter this figure belongs to. Compound figures fill whole
   * dotted-quarter beats and are only offered, and only generated, in 6/8,
   * 9/8 and 12/8; simple figures only in 2/4, 3/4 and 4/4. Optional only so
   * figures built elsewhere (nct-patterns, cadence notes) type-check: every
   * entry in this catalogue sets it (tests/unit/rhythm-catalogue.test.ts).
   */
  meterKind?: "simple" | "compound";
  /** The compound picker's group. Simple figures group by notes and rests. */
  pickerGroup?: "Core" | "Rests" | "Sixteenths";
  isPatternNote?: boolean;
  isPatternStart?: boolean;
  isPatternEnd?: boolean;
  patternIndex?: number | null;
}

export const rhythms: Rhythm[] = [
  {
    name: "thirtySecond",
    abcValue: ["1"],
    meterValue: [1 / 32],
    totalValue: 1,
    rest: false,
    oddsWeight: 5,
    pattern: false,
    maxRng: 0,
    symbol: "𝄽",
    weight: 5,
    meterKind: "simple",
  },
  {
    name: "thirtySecondRest",
    abcValue: ["z1"],
    meterValue: [1 / 32],
    totalValue: 1,
    rest: true,
    oddsWeight: 2,
    pattern: false,
    maxRng: 0,
    symbol: "𝄻",
    weight: 2,
    meterKind: "simple",
  },
  {
    name: "sixteenthRest",
    abcValue: ["z2"],
    meterValue: [1 / 16],
    totalValue: 2,
    rest: true,
    oddsWeight: 3,
    maxRng: 0,
    pattern: false,
    symbol: "𝄽",
    weight: 3,
    meterKind: "simple",
  },
  {
    name: "dotSixteenthRest",
    abcValue: ["z3"],
    meterValue: [3 / 32],
    totalValue: 3,
    rest: true,
    oddsWeight: 2,
    maxRng: 0,
    pattern: false,
    symbol: "𝄽",
    weight: 2,
    meterKind: "simple",
  },
  {
    name: "eighthRest",
    abcValue: ["z4"],
    meterValue: [1 / 8],
    totalValue: 4,
    rest: true,
    oddsWeight: 4,
    maxRng: 0,
    pattern: false,
    symbol: "𝄾",
    weight: 4,
    meterKind: "simple",
  },
  {
    name: "dotEighthRest",
    abcValue: ["z6"],
    meterValue: [3 / 16],
    totalValue: 6,
    rest: true,
    oddsWeight: 2,
    maxRng: 0,
    pattern: false,
    symbol: "𝄾",
    weight: 2,
    meterKind: "simple",
  },
  {
    name: "quarter",
    abcValue: ["8"],
    meterValue: [1 / 4],
    totalValue: 8,
    rest: false,
    oddsWeight: 10,
    maxRng: 0,
    pattern: false,
    symbol: "𝄘",
    weight: 10,
    meterKind: "simple",
  },
  {
    name: "quarterRest",
    abcValue: ["z8"],
    meterValue: [1 / 4],
    totalValue: 8,
    rest: true,
    oddsWeight: 3,
    maxRng: 0,
    pattern: false,
    symbol: "𝄽",
    weight: 3,
    meterKind: "simple",
  },
  {
    name: "dotQuarter",
    abcValue: ["12"],
    meterValue: [3 / 8],
    totalValue: 12,
    rest: false,
    oddsWeight: 6,
    maxRng: 0,
    pattern: false,
    symbol: "𝄘•",
    weight: 6,
    meterKind: "compound",
    pickerGroup: "Core",
  },
  {
    name: "dotQuarterRest",
    abcValue: ["z12"],
    meterValue: [3 / 8],
    totalValue: 12,
    rest: true,
    oddsWeight: 3,
    maxRng: 0,
    pattern: false,
    symbol: "𝄽",
    weight: 3,
    meterKind: "compound",
    pickerGroup: "Rests",
  },
  {
    name: "half",
    abcValue: ["16"],
    meterValue: [1 / 2],
    totalValue: 16,
    rest: false,
    oddsWeight: 8,
    maxRng: 0,
    pattern: false,
    symbol: "𝄗",
    weight: 8,
    meterKind: "simple",
  },
  {
    name: "halfRest",
    abcValue: ["z16"],
    meterValue: [1 / 2],
    totalValue: 16,
    rest: true,
    oddsWeight: 2,
    maxRng: 0,
    pattern: false,
    symbol: "��",
    weight: 2,
    meterKind: "simple",
  },
  {
    name: "dotHalf",
    abcValue: ["24"],
    meterValue: [3 / 4],
    totalValue: 24,
    rest: false,
    oddsWeight: 4,
    maxRng: 0,
    pattern: false,
    symbol: "𝄗•",
    weight: 4,
    meterKind: "simple",
  },
  {
    name: "dotHalfRest",
    abcValue: ["z24"],
    meterValue: [3 / 4],
    totalValue: 24,
    rest: true,
    oddsWeight: 1,
    maxRng: 0,
    pattern: false,
    symbol: "𝄼",
    weight: 1,
    meterKind: "compound",
    pickerGroup: "Rests",
  },
  {
    name: "whole",
    abcValue: ["32"],
    meterValue: [1],
    totalValue: 32,
    rest: false,
    oddsWeight: 4,
    maxRng: 0,
    pattern: false,
    symbol: "𝄖",
    weight: 4,
    meterKind: "simple",
  },
  {
    name: "wholeRest",
    abcValue: ["z32"],
    meterValue: [1],
    totalValue: 32,
    rest: true,
    oddsWeight: 1,
    maxRng: 0,
    pattern: false,
    symbol: "𝄻",
    weight: 1,
    meterKind: "simple",
  },
  {
    name: "eighthRestEighth",
    abcValue: ["z4", "4"],
    meterValue: [1 / 8, 1 / 8],
    totalValue: 8,
    rest: false,
    oddsWeight: 8,
    maxRng: 0,
    pattern: true,
    symbol: "𝄾𝄙",
    weight: 8,
    meterKind: "simple",
  },
  {
    name: "eighthEighth",
    abcValue: ["4", "4"],
    meterValue: [1 / 8, 1 / 8],
    totalValue: 8,
    rest: false,
    oddsWeight: 8,
    maxRng: 0,
    pattern: true,
    symbol: "𝄙𝄙",
    weight: 8,
    meterKind: "simple",
  },
  {
    name: "fourSixteenths",
    abcValue: ["2", "2", "2", "2"],
    meterValue: [1 / 16, 1 / 16, 1 / 16, 1 / 16],
    totalValue: 8,
    rest: false,
    oddsWeight: 6,
    maxRng: 0,
    pattern: true,
    symbol: "𝄚𝄚𝄚𝄚",
    weight: 6,
    meterKind: "simple",
  },
  {
    name: "eighthSixteenthSixteenth",
    abcValue: ["4", "2", "2"],
    meterValue: [1 / 8, 1 / 16, 1 / 16],
    totalValue: 8,
    rest: false,
    oddsWeight: 6,
    maxRng: 0,
    pattern: true,
    symbol: "𝄙𝄚𝄚",
    weight: 6,
    meterKind: "simple",
  },
  {
    name: "sixteenthSixteenthEighth",
    abcValue: ["2", "2", "4"],
    meterValue: [1 / 16, 1 / 16, 1 / 8],
    totalValue: 8,
    rest: false,
    oddsWeight: 6,
    maxRng: 0,
    pattern: true,
    symbol: "𝄚𝄚𝄙",
    weight: 6,
    meterKind: "simple",
  },
  {
    name: "sixteenthEighthSixteenth",
    abcValue: ["2", "4", "2"],
    meterValue: [1 / 16, 1 / 8, 1 / 16],
    totalValue: 8,
    rest: false,
    oddsWeight: 6,
    maxRng: 0,
    pattern: true,
    symbol: "𝄚𝄙𝄚",
    weight: 6,
    meterKind: "simple",
  },
  {
    name: "dotEighthSixteenth",
    abcValue: ["6", "2"],
    meterValue: [3 / 16, 1 / 16],
    totalValue: 8,
    rest: false,
    oddsWeight: 6,
    maxRng: 0,
    pattern: true,
    symbol: "𝄙•𝄚",
    weight: 6,
    meterKind: "simple",
  },
  {
    // Weighted well above its neighbours on purpose, and it is still not
    // over-represented. `favorLongerNotes` multiplies any rhythm containing an
    // eighth by 0.15 (see speedFactorFor), so this figure was being crushed
    // 6.7x against the quarters and halves whatever its weight said: selected at
    // UIL 4 it appeared 0.071 times a bar, one in every fourteen.
    //
    // The transcriptions write it at 0.193 a bar (Forgotten) and 0.125
    // (Summer Rains). Measured over 30 exercises, weight 12 gives 0.138 and
    // weight 20 gives 0.188 - so 20, which lands on the real music. The quarter
    // still takes 48% of all steps; this takes 8.5%.
    name: "dotQuarterEighth",
    abcValue: ["12", "4"],
    meterValue: [3 / 8, 1 / 8],
    totalValue: 16,
    rest: false,
    oddsWeight: 5,
    maxRng: 0,
    pattern: true,
    symbol: "𝄘•𝄙",
    weight: 20,
    meterKind: "simple",
  },
  {
    // The reverse of dotQuarterEighth: the short note first, so the long one
    // begins off the beat. Two beats long and only fits starting on a beat.
    //
    // Added in place of the bare dotted quarter, which was removed: on its own a
    // dotted quarter is one and a half beats, so it leaves everything after it
    // starting off the beat with nothing to resolve against. Paired with the
    // eighth here, the figure closes its own syncopation and lands the next note
    // back on a beat.
    name: "eighthDotQuarter",
    abcValue: ["4", "12"],
    meterValue: [1 / 8, 3 / 8],
    totalValue: 16,
    rest: false,
    oddsWeight: 4,
    maxRng: 0,
    pattern: true,
    symbol: "\ud834\udd19\ud834\udd18\u2022",
    weight: 4,
    meterKind: "simple",
  },
  {
    // Syncopation: the quarter straddles the beat, so the figure is two beats
    // long and only fits starting on a beat. Kodály names it syn-co-pa.
    name: "eighthQuarterEighth",
    abcValue: ["4", "8", "4"],
    meterValue: [1 / 8, 1 / 4, 1 / 8],
    totalValue: 16,
    rest: false,
    oddsWeight: 5,
    maxRng: 0,
    pattern: true,
    symbol: "𝄙𝄘𝄙",
    weight: 5,
    meterKind: "simple",
  },
  {
    name: "dotHalfQuarter",
    abcValue: ["24", "8"],
    meterValue: [3 / 4, 1 / 4],
    totalValue: 32,
    rest: false,
    oddsWeight: 3,
    maxRng: 0,
    pattern: true,
    symbol: "𝄗•𝄘",
    weight: 3,
    meterKind: "simple",
  },
  // ── Compound meter: 6/8, 9/8, 12/8 ────────────────────────────────────────
  // Every figure fills one dotted-quarter beat (12) or two (24), so compound
  // bars fill beat by beat and nothing lands off the beat (compound-rhythm.ts).
  // Weights are a starting point, not measured against repertoire yet.
  {
    name: "threeEighths",
    abcValue: ["4", "4", "4"],
    meterValue: [1 / 8, 1 / 8, 1 / 8],
    totalValue: 12,
    rest: false,
    oddsWeight: 8,
    maxRng: 0,
    pattern: true,
    symbol: "𝄙𝄙𝄙",
    weight: 8,
    meterKind: "compound",
    pickerGroup: "Core",
  },
  {
    name: "quarterEighth",
    abcValue: ["8", "4"],
    meterValue: [1 / 4, 1 / 8],
    totalValue: 12,
    rest: false,
    oddsWeight: 8,
    maxRng: 0,
    pattern: true,
    symbol: "𝄘𝄙",
    weight: 8,
    meterKind: "compound",
    pickerGroup: "Core",
  },
  {
    name: "eighthQuarter",
    abcValue: ["4", "8"],
    meterValue: [1 / 8, 1 / 4],
    totalValue: 12,
    rest: false,
    oddsWeight: 4,
    maxRng: 0,
    pattern: true,
    symbol: "𝄙𝄘",
    weight: 4,
    meterKind: "compound",
    pickerGroup: "Core",
  },
  {
    // The dotted half of compound meter: two beats. A separate entry from
    // the simple dotHalf, which is three quarter beats of 3/4.
    name: "dotHalfCompound",
    abcValue: ["24"],
    meterValue: [3 / 4],
    totalValue: 24,
    rest: false,
    oddsWeight: 4,
    maxRng: 0,
    pattern: false,
    symbol: "𝄗•",
    weight: 4,
    meterKind: "compound",
    pickerGroup: "Core",
  },
  {
    name: "quarterEighthRest",
    abcValue: ["8", "z4"],
    meterValue: [1 / 4, 1 / 8],
    totalValue: 12,
    rest: false,
    oddsWeight: 2,
    maxRng: 0,
    pattern: true,
    symbol: "𝄘𝄾",
    weight: 2,
    meterKind: "compound",
    pickerGroup: "Rests",
  },
  {
    name: "eighthRestTwoEighths",
    abcValue: ["z4", "4", "4"],
    meterValue: [1 / 8, 1 / 8, 1 / 8],
    totalValue: 12,
    rest: false,
    oddsWeight: 2,
    maxRng: 0,
    pattern: true,
    symbol: "𝄾𝄙𝄙",
    weight: 2,
    meterKind: "compound",
    pickerGroup: "Rests",
  },
  {
    name: "twoEighthsEighthRest",
    abcValue: ["4", "4", "z4"],
    meterValue: [1 / 8, 1 / 8, 1 / 8],
    totalValue: 12,
    rest: false,
    oddsWeight: 2,
    maxRng: 0,
    pattern: true,
    symbol: "𝄙𝄙𝄾",
    weight: 2,
    meterKind: "compound",
    pickerGroup: "Rests",
  },
  {
    name: "sixSixteenths",
    abcValue: ["2", "2", "2", "2", "2", "2"],
    meterValue: [1 / 16, 1 / 16, 1 / 16, 1 / 16, 1 / 16, 1 / 16],
    totalValue: 12,
    rest: false,
    oddsWeight: 4,
    maxRng: 0,
    pattern: true,
    symbol: "𝄚𝄚𝄚𝄚𝄚𝄚",
    weight: 4,
    meterKind: "compound",
    pickerGroup: "Sixteenths",
  },
  {
    name: "twoSixteenthsTwoEighths",
    abcValue: ["2", "2", "4", "4"],
    meterValue: [1 / 16, 1 / 16, 1 / 8, 1 / 8],
    totalValue: 12,
    rest: false,
    oddsWeight: 3,
    maxRng: 0,
    pattern: true,
    symbol: "𝄚𝄚𝄙𝄙",
    weight: 3,
    meterKind: "compound",
    pickerGroup: "Sixteenths",
  },
  {
    name: "eighthTwoSixteenthsEighth",
    abcValue: ["4", "2", "2", "4"],
    meterValue: [1 / 8, 1 / 16, 1 / 16, 1 / 8],
    totalValue: 12,
    rest: false,
    oddsWeight: 3,
    maxRng: 0,
    pattern: true,
    symbol: "𝄙𝄚𝄚𝄙",
    weight: 3,
    meterKind: "compound",
    pickerGroup: "Sixteenths",
  },
  {
    name: "twoEighthsTwoSixteenths",
    abcValue: ["4", "4", "2", "2"],
    meterValue: [1 / 8, 1 / 8, 1 / 16, 1 / 16],
    totalValue: 12,
    rest: false,
    oddsWeight: 3,
    maxRng: 0,
    pattern: true,
    symbol: "𝄙𝄙𝄚𝄚",
    weight: 3,
    meterKind: "compound",
    pickerGroup: "Sixteenths",
  },
  {
    name: "quarterTwoSixteenths",
    abcValue: ["8", "2", "2"],
    meterValue: [1 / 4, 1 / 16, 1 / 16],
    totalValue: 12,
    rest: false,
    oddsWeight: 3,
    maxRng: 0,
    pattern: true,
    symbol: "𝄘𝄚𝄚",
    weight: 3,
    meterKind: "compound",
    pickerGroup: "Sixteenths",
  },
];
