export interface Rhythm {
  weight: number;
  name: string;
  abcValue: string[];
  meterValue: number[];
  totalValue: number;
  singleNoteValue?: number; // Value of individual note in a pattern
  rest: boolean;
  oddsWeight: number;
  maxRng: number;
  pattern?: boolean;
  symbol: string;
  isPatternNote?: boolean;
  isPatternStart?: boolean;
  isPatternEnd?: boolean;
  patternIndex?: number | null;
}

export const rhythms: Rhythm[] = [
  {
    name: "thirtySecond",
    abcValue: ["1"],
    meterValue: [1 / 32],
    totalValue: 1,
    rest: false,
    oddsWeight: 5,
    pattern: false,
    maxRng: 0,
    symbol: "𝄽",
    weight: 5,
  },
  {
    name: "thirtySecondRest",
    abcValue: ["1"],
    meterValue: [1 / 32],
    totalValue: 1,
    rest: true,
    oddsWeight: 2,
    pattern: false,
    maxRng: 0,
    symbol: "𝄻",
    weight: 2,
  },
  {
    name: "sixteenthRest",
    abcValue: ["2"],
    meterValue: [1 / 16],
    totalValue: 2,
    rest: true,
    oddsWeight: 3,
    maxRng: 0,
    pattern: false,
    symbol: "𝄽",
    weight: 3,
  },
  {
    name: "dotSixteenthRest",
    abcValue: ["3"],
    meterValue: [1 / 16],
    totalValue: 3,
    rest: true,
    oddsWeight: 2,
    maxRng: 0,
    pattern: false,
    symbol: "𝄽",
    weight: 2,
  },
  {
    name: "eighthRest",
    abcValue: ["4"],
    meterValue: [1 / 8],
    totalValue: 4,
    rest: true,
    oddsWeight: 4,
    maxRng: 0,
    pattern: false,
    symbol: "𝄾",
    weight: 4,
  },
  {
    name: "dotEighthRest",
    abcValue: ["6"],
    meterValue: [1 / 8],
    totalValue: 5,
    rest: true,
    oddsWeight: 2,
    maxRng: 0,
    pattern: false,
    symbol: "𝄾",
    weight: 2,
  },
  {
    name: "quarter",
    abcValue: ["8"],
    meterValue: [1 / 4],
    totalValue: 8,
    rest: false,
    oddsWeight: 10,
    maxRng: 0,
    pattern: false,
    symbol: "𝄘",
    weight: 10,
  },
  {
    name: "quarterRest",
    abcValue: ["8"],
    meterValue: [1 / 4],
    totalValue: 8,
    rest: true,
    oddsWeight: 3,
    maxRng: 0,
    pattern: false,
    symbol: "𝄽",
    weight: 3,
  },
  {
    name: "dotQuarter",
    abcValue: ["12"],
    meterValue: [3 / 8],
    totalValue: 12,
    rest: false,
    oddsWeight: 6,
    maxRng: 0,
    pattern: false,
    symbol: "𝄘•",
    weight: 6,
  },
  {
    name: "dotQuarterRest",
    abcValue: ["10"],
    meterValue: [1 / 4],
    totalValue: 10,
    rest: true,
    oddsWeight: 2,
    maxRng: 0,
    pattern: false,
    symbol: "𝄽",
    weight: 2,
  },
  {
    name: "half",
    abcValue: ["16"],
    meterValue: [1 / 2],
    totalValue: 16,
    rest: false,
    oddsWeight: 8,
    maxRng: 0,
    pattern: false,
    symbol: "𝄗",
    weight: 8,
  },
  {
    name: "halfRest",
    abcValue: ["16"],
    meterValue: [1 / 2],
    totalValue: 16,
    rest: true,
    oddsWeight: 2,
    maxRng: 0,
    pattern: false,
    symbol: "��",
    weight: 2,
  },
  {
    name: "dotHalf",
    abcValue: ["24"],
    meterValue: [3 / 4],
    totalValue: 24,
    rest: false,
    oddsWeight: 4,
    maxRng: 0,
    pattern: false,
    symbol: "𝄗•",
    weight: 4,
  },
  {
    name: "dotHalfRest",
    abcValue: ["20"],
    meterValue: [1 / 2],
    totalValue: 24,
    rest: true,
    oddsWeight: 1,
    maxRng: 0,
    pattern: false,
    symbol: "𝄼",
    weight: 1,
  },
  {
    name: "whole",
    abcValue: ["32"],
    meterValue: [1],
    totalValue: 32,
    rest: false,
    oddsWeight: 4,
    maxRng: 0,
    pattern: false,
    symbol: "𝄖",
    weight: 4,
  },
  {
    name: "wholeRest",
    abcValue: ["z32"],
    meterValue: [1],
    totalValue: 32,
    rest: true,
    oddsWeight: 1,
    maxRng: 0,
    pattern: false,
    symbol: "𝄻",
    weight: 1,
  },
  {
    name: "eighthEighth",
    abcValue: ["4", "4"],
    meterValue: [1 / 8, 1 / 8],
    totalValue: 8,
    rest: false,
    oddsWeight: 8,
    maxRng: 0,
    pattern: true,
    symbol: "𝄙𝄙",
    weight: 8,
  },
  {
    name: "fourSixteenths",
    abcValue: ["2", "2", "2", "2"],
    meterValue: [1 / 16, 1 / 16, 1 / 16, 1 / 16],
    totalValue: 8,
    rest: false,
    oddsWeight: 6,
    maxRng: 0,
    pattern: true,
    symbol: "𝄚𝄚𝄚𝄚",
    weight: 6,
  },
  {
    name: "eighthSixteenthSixteenth",
    abcValue: ["4", "2", "2"],
    meterValue: [1 / 8, 1 / 16, 1 / 16],
    totalValue: 8,
    rest: false,
    oddsWeight: 6,
    maxRng: 0,
    pattern: true,
    symbol: "𝄙𝄚𝄚",
    weight: 6,
  },
  {
    name: "sixteenthSixteenthEighth",
    abcValue: ["2", "2", "4"],
    meterValue: [1 / 16, 1 / 16, 1 / 8],
    totalValue: 8,
    rest: false,
    oddsWeight: 6,
    maxRng: 0,
    pattern: true,
    symbol: "𝄚𝄚𝄙",
    weight: 6,
  },
  {
    name: "dotEighthSixteenth",
    abcValue: ["6", "2"],
    meterValue: [3 / 16, 1 / 16],
    totalValue: 8,
    rest: false,
    oddsWeight: 6,
    maxRng: 0,
    pattern: true,
    symbol: "𝄙•𝄚",
    weight: 6,
  },
  {
    name: "dotQuarterEighth",
    abcValue: ["12", "4"],
    meterValue: [3 / 8, 1 / 8],
    totalValue: 16,
    rest: false,
    oddsWeight: 5,
    maxRng: 0,
    pattern: true,
    symbol: "𝄘•𝄙",
    weight: 5,
  },
  {
    name: "dotHalfQuarter",
    abcValue: ["24", "8"],
    meterValue: [3 / 4, 1 / 4],
    totalValue: 32,
    rest: false,
    oddsWeight: 3,
    maxRng: 0,
    pattern: true,
    symbol: "𝄗•𝄘",
    weight: 3,
  },
];
