import { writable } from "svelte/store";

/**
 * The count-in, as a director says it: "1, 2, Ready, Go" in 4/4, "1, Ready,
 * Go" in 3/4. 2/4 is counted in over two bars so it gets the same four words -
 * one bar of two is too short to get a choir breathing together. Tested in
 * tests/unit/count-in.test.ts.
 *
 * The practice pages play this many bars before the music (abcjs's
 * extraMeasuresAtBeginning, and the drum intro on the Choral page), and set
 * `countInWordNow` on each beat of it for CountInOverlay to show.
 */

const beatsPerBar = (meter: string) => parseInt(meter, 10) || 4;

export const countInMeasures = (meter: string) => (beatsPerBar(meter) === 2 ? 2 : 1);

export const countInBeats = (meter: string) => countInMeasures(meter) * beatsPerBar(meter);

export function countInWords(meter: string): string[] {
  const beats = countInBeats(meter);
  // The last two beats are always "Ready, Go"; the numbers count up to them.
  return [...Array.from({ length: beats - 2 }, (_, i) => String(i + 1)), "Ready", "Go"];
}

/** The word for this moment of the count-in, or null outside it. `beat` is abcjs's, from 0, fractional between beats. */
export function countInWord(meter: string, beat: number): string | null {
  const whole = Math.floor(beat);
  if (whole < 0 || whole >= countInBeats(meter)) return null;
  return countInWords(meter)[whole];
}

/** The word showing now, with its beat so the same word twice still animates. Null hides it. */
export const countInWordNow = writable<{ word: string; beat: number } | null>(null);

/** Sets the overlay from a beat callback. Cheap to call on every subdivision. */
export function showCountIn(meter: string, beat: number) {
  const word = countInWord(meter, beat);
  const whole = Math.floor(beat);
  countInWordNow.update((now) => {
    if (!word) return now ? null : now;
    return now?.beat === whole ? now : { word, beat: whole };
  });
}

export const hideCountIn = () => countInWordNow.set(null);

/** The meter of a parsed abcjs tune, "3/4", or the fallback if it has none. */
export function meterOf(tune: { getMeterFraction?: () => { num: number; den: number } } | null | undefined, fallback: string) {
  const f = tune?.getMeterFraction?.();
  return f && f.num && f.den ? `${f.num}/${f.den}` : fallback;
}

type Rect = { x: number; y: number; w: number; h: number };

/**
 * Where the count-in word sits: the top-left of the music, in the gap above
 * the first staff, below any text (title, "Generated by", the tempo mark)
 * that reaches that corner - so it never covers a note. Sized to the gap, up
 * to 64px tall; null if there is no room at all, rather than on the staff.
 * Coordinates are relative to the score's wrapper.
 */
export function countInBadge(p: { paperTop: number; paperLeft: number; staffTop: number; obstacles: Rect[] }) {
  const left = p.paperLeft + 12;
  const bottom = p.staffTop - 4;
  // Wide enough for the longest word, "Ready", with its padding.
  const widthFor = (height: number) => Math.round(height * 2.75);
  // Largest first: the biggest badge that fits in the corner, clear of every
  // piece of text whose span it would share.
  for (let height = 64; height >= 20; height -= 2) {
    const width = widthFor(height);
    // 10px of air beside anything to the right - the tempo mark's note.
    const inTheWay = p.obstacles.filter((o) => o.x < left + width + 10 && o.x + o.w > left && o.y < bottom);
    const top = Math.max(p.paperTop + 4, ...inTheWay.map((o) => o.y + o.h + 4));
    if (bottom - top >= height) {
      return { top: bottom - height, left, width, height, fontSize: Math.round(height * 0.72) };
    }
  }
  return null;
}

/** Whether the word is showing on the score; if not, the playback bar shows it instead. */
export const countInOnScore = writable(false);
