import { prepareVoiceParts } from "./prep-params";
import { generateRandomRhythm } from "./rhythm-generation";
import { generateChordProgression } from "./chord-generation";
import { buildChordNotes } from "./build-chord-notes";
import { assembleAbcString } from "./abc-assembly";
import type {
  Chord,
  Rhythm,
  VoicePart,
  VoiceNote,
  TimeSignature,
  PartDefinition,
  PartsObject,
  Note,
} from "./types";

// Interface for the main function parameters
export interface GenerateChoralParams {
  key: string;
  timeSig: TimeSignature;
  partsObject: PartsObject; // Contains info about voices, ranges, clefs
  level: number; // Difficulty level (might affect range, rhythm complexity, etc.)
  measures: number;
  maxSkip: number;
  bpm: number;
  selectedRhythms: Rhythm[];
  chords: Chord[]; // Add chords to the interface
  // Add any other necessary parameters like title, composer, etc.
  title?: string;
  composer?: string;
}

/**
 * Orchestrates the generation of a choral sight-reading exercise.
 *
 * @param params - The parameters for generation.
 * @returns An object containing the final ABC string and the generated chord progression.
 */
export function generateChoralExercise(params: GenerateChoralParams): {
  abcString: string;
  chordProgression: Chord[];
} {
  console.log("--- generateChoralExercise START ---");
  console.log("Received params:", JSON.stringify(params, null, 2));

  const {
    key,
    timeSig,
    partsObject,
    level,
    measures,
    maxSkip,
    bpm,
    selectedRhythms,
    chords,
  } = params;

  // --- Input Validation ---
  if (!selectedRhythms || selectedRhythms.length === 0) {
    throw new Error("No rhythms selected for generation.");
  }
  if (!chords || chords.length === 0) {
    throw new Error("No chords provided for generation.");
  }
  // Add more validation as needed...

  // --- Generation Pipeline ---

  // 1. Prepare Voice Parts
  console.log("1. Preparing Voice Parts...");
  const partRanges = Object.fromEntries(
    Object.entries(partsObject.parts).map(([name, part]) => [name, part.range])
  );
  const voiceParts: VoicePart[] = prepareVoiceParts(
    key,
    partRanges,
    partsObject
  );
  console.log(`  Prepared ${voiceParts.length} voice parts.`);
  console.log(voiceParts);

  // 2. Generate Rhythm
  console.log("2. Generating Rhythm...");
  console.log(
    `  Params: timeSig=${timeSig.name}, measures=${measures}, selectedRhythms count=${selectedRhythms.length}`
  );
  const generatedRhythms = generateRandomRhythm(
    timeSig,
    measures,
    selectedRhythms
  );
  const finalRhythms: Rhythm[] = generatedRhythms as Rhythm[];
  const numNotes = finalRhythms.filter((r) => !r.rest).length;
  console.log(
    `  Generated ${finalRhythms.length} rhythm steps, ${numNotes} non-rest notes.`
  );

  // 4. Generate Chord Progression & Bass Line
  console.log("3. Generating Chord Progression & Bass Line...");
  const bassRange = voiceParts.find((p) => p.order === 0)?.range;
  if (!bassRange) {
    throw new Error("Bass voice part not found or has no range.");
  }
  console.log(
    `  Params: chords count=${
      chords.length
    }, numNotes=${numNotes}, bassRange=[${bassRange.join(
      ", "
    )}], maxSkip=${maxSkip}, key=${key}`
  );
  const result = generateChordProgression(
    chords,
    numNotes,
    bassRange,
    maxSkip,
    key
  );
  const chordProgression = result.progression;
  const bassLine = result.bassLine;
  console.log(
    `  Generated progression length=${chordProgression.length}, bass line length=${bassLine.length}`
  );

  // 5. Build Chord Notes for All Voices
  console.log("4. Building Chord Notes...");
  console.log(
    `  Params: key=${key}, rhythms count=${finalRhythms.length}, progression count=${chordProgression.length}, voiceParts count=${voiceParts.length}, bassLine count=${bassLine.length}`
  );
  const voiceNotes: VoiceNote[][] = buildChordNotes(
    key,
    finalRhythms,
    chordProgression,
    voiceParts,
    bassLine,
    maxSkip
  );
  console.log(`  Built notes for ${voiceNotes.length} voices.`);

  // 6. Assemble ABC Notation String
  console.log("5. Assembling ABC String...");
  const abcParams = {
    title: params.title || `Sight Reading Exercise - Level ${level} - ${key}`,
    composer: params.composer || "Generated by SightReadingApp",
    // meter: timeSig.name, // Removed, passed separately
    // defaultLength: "1/32", // Removed, handled in assembleAbcString
    // key: key, // Removed, passed separately
    tempo: bpm,
  };
  console.log(
    `  Params: voiceNotes count=${voiceNotes.length}, voiceParts count=${
      voiceParts.length
    }, rhythms count=${finalRhythms.length}, key=${key}, timeSig=${
      timeSig.name
    }, metadata=${JSON.stringify(abcParams)}`
  );
  const abcString = assembleAbcString(
    voiceNotes,
    voiceParts,
    finalRhythms,
    key,
    timeSig,
    abcParams
  );

  console.log(abcString);

  console.log("--- generateChoralExercise END ---");
  // Return results
  return {
    abcString,
    chordProgression: chordProgression,
  };
}
