<script lang="ts">
  import { onDestroy } from "svelte";
  import { countInBadge, countInOnScore, countInWordNow } from "../lib/count-in";

  /**
   * The count-in word at the top-left of the music, in the gap above the
   * first staff and clear of the title, "Generated by" and the tempo mark -
   * measured from the score as drawn when the count-in starts. Goes inside the
   * score's positioned wrapper, beside #paper. Where there is no room, it
   * stays out, and the playback bar shows the word instead.
   */

  let wrap: HTMLDivElement;
  let box: ReturnType<typeof countInBadge> = null;
  let measuredAt: number | null = null;

  function measure() {
    const host = wrap?.parentElement;
    const paper = host?.querySelector<HTMLElement>("#paper");
    const staff = paper?.querySelector(".abcjs-staff");
    if (!host || !paper || !staff) return null;
    const h = host.getBoundingClientRect();
    const rel = (r: DOMRect) => ({ x: r.left - h.left, y: r.top - h.top, w: r.width, h: r.height });
    const obstacles = [...paper.querySelectorAll("text, .abcjs-tempo, .abcjs-title, .abcjs-subtitle")]
      .map((el) => rel(el.getBoundingClientRect()))
      .filter((r) => r.w > 0 && r.h > 0);
    const p = rel(paper.getBoundingClientRect());
    // The top of the music is the staff, or a note in the first line reaching
    // above it - a high note's stem, a ledger line - whichever is higher.
    const firstLine = [staff, ...paper.querySelectorAll(".abcjs-l0.abcjs-note, .abcjs-l0.abcjs-rest, .abcjs-l0.abcjs-ledger")];
    const musicTop = Math.min(...firstLine.map((el) => rel(el.getBoundingClientRect())).filter((r) => r.h > 0).map((r) => r.y));
    return countInBadge({ paperTop: p.y, paperLeft: p.x, staffTop: musicTop, obstacles });
  }

  // Measured once per count-in, on its first word: the score does not move under it.
  const unsubscribe = countInWordNow.subscribe((now) => {
    if (!now) {
      measuredAt = null;
      countInOnScore.set(false);
      return;
    }
    if (measuredAt === null || now.beat < measuredAt) {
      box = measure();
      measuredAt = now.beat;
      countInOnScore.set(!!box);
    }
  });
  onDestroy(() => {
    unsubscribe();
    countInOnScore.set(false);
  });
</script>

<div bind:this={wrap} class="contents">
  {#if $countInWordNow && box}
    {#key $countInWordNow.beat}
      <div
        class="badge no-print"
        style="top: {box.top}px; left: {box.left}px; height: {box.height}px; min-width: {box.width}px; font-size: {box.fontSize}px"
        aria-live="assertive"
        aria-atomic="true"
      >
        <span class:go={$countInWordNow.word === "Go"}>{$countInWordNow.word}</span>
      </div>
    {/key}
  {/if}
</div>

<style>
  .badge {
    position: absolute;
    z-index: 5;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 0 0.3em;
    border-radius: 0.28em;
    background: var(--sr-countin-bg, #17566b);
    color: var(--sr-countin-ink, #fff);
    font-family: var(--sr-font-display, inherit);
    font-weight: 800;
    line-height: 1;
    pointer-events: none;
    box-shadow: 0 4px 14px rgb(0 0 0 / 0.18);
  }
  span {
    display: inline-block;
    animation: pop 0.3s cubic-bezier(0.2, 0.9, 0.3, 1.3) both;
  }
  .go {
    color: var(--sr-countin-go, #b9e6f5);
  }
  @keyframes pop {
    from { transform: scale(1.4); opacity: 0; }
    to { transform: scale(1); opacity: 1; }
  }
  @media (prefers-reduced-motion: reduce) {
    span { animation: none; }
  }
</style>
