import { describe, expect, test } from "bun:test";
import { countInBadge, countInBeats, countInMeasures, countInWord, countInWords } from "../../src/lib/count-in";

/**
 * The spoken count-in, shown on screen beat by beat: "1, 2, Ready, Go" in 4/4
 * and 2/4, "1, Ready, Go" in 3/4 - the way a director counts a choir in.
 * Written before the code.
 */

describe("what is said", () => {
  test("four beats in 4/4, three in 3/4", () => {
    expect(countInWords("4/4")).toEqual(["1", "2", "Ready", "Go"]);
    expect(countInWords("3/4")).toEqual(["1", "Ready", "Go"]);
  });

  test("2/4 takes two bars, so it is counted in the same four words", () => {
    expect(countInMeasures("2/4")).toBe(2);
    expect(countInWords("2/4")).toEqual(["1", "2", "Ready", "Go"]);
  });

  test("one bar in the other meters", () => {
    expect(countInMeasures("4/4")).toBe(1);
    expect(countInMeasures("3/4")).toBe(1);
    expect(countInBeats("4/4")).toBe(4);
    expect(countInBeats("3/4")).toBe(3);
    expect(countInBeats("2/4")).toBe(4);
  });
});

describe("the word on each beat", () => {
  test("from the first beat of the count-in to the last", () => {
    expect([0, 1, 2, 3].map((b) => countInWord("4/4", b))).toEqual(["1", "2", "Ready", "Go"]);
    expect([0, 1, 2].map((b) => countInWord("3/4", b))).toEqual(["1", "Ready", "Go"]);
  });

  test("abcjs reports fractions of a beat; the word holds for the whole beat", () => {
    expect(countInWord("4/4", 2.5)).toBe("Ready");
    expect(countInWord("3/4", 0.9375)).toBe("1");
  });

  test("nothing once the music starts, or before", () => {
    expect(countInWord("4/4", 4)).toBe(null);
    expect(countInWord("3/4", 3)).toBe(null);
    expect(countInWord("2/4", 4)).toBe(null);
    expect(countInWord("4/4", -1)).toBe(null);
  });
});

describe("where the word goes: top-left of the music, clear of the staff", () => {
  // Measured from the real pages: the Choral page on a desktop, then on a phone,
  // where the title and "Generated by" fill the top-left; the Unison page has no title.
  test("in the empty corner above the first staff", () => {
    const b = countInBadge({ paperTop: 8, paperLeft: 0, staffTop: 161, obstacles: [
      { x: 330, y: 37, w: 333, h: 34 }, { x: 703, y: 82, w: 273, h: 24 }, { x: 190, y: 119, w: 41, h: 25 },
    ] })!;
    expect(b.top + b.height).toBeLessThanOrEqual(161 - 4);
    // As large as the corner allows while keeping clear of the tempo mark.
    expect(b.height).toBeGreaterThanOrEqual(50);
    expect(b.left + b.width + 10).toBeLessThanOrEqual(190);
    expect(b.left).toBe(12);
  });

  test("below the title when the title reaches the corner", () => {
    const b = countInBadge({ paperTop: 8, paperLeft: 0, staffTop: 143, obstacles: [
      { x: 24, y: 34, w: 294, h: 30 }, { x: 86, y: 73, w: 241, h: 21 }, { x: 168, y: 106, w: 36, h: 22 },
    ] })!;
    expect(b.top).toBeGreaterThanOrEqual(94);
    expect(b.top + b.height).toBeLessThanOrEqual(143 - 4);
    // Wide enough for "Ready" without reaching the tempo mark.
    expect(b.left + b.width).toBeLessThanOrEqual(168);
  });

  test("small, but still there, in a tight gap", () => {
    const b = countInBadge({ paperTop: 8, paperLeft: 0, staffTop: 45, obstacles: [] })!;
    expect(b.top).toBeGreaterThanOrEqual(8);
    expect(b.top + b.height).toBeLessThanOrEqual(45 - 4);
    expect(b.fontSize).toBeGreaterThanOrEqual(14);
  });

  test("nowhere at all rather than on the staff", () => {
    expect(countInBadge({ paperTop: 8, paperLeft: 0, staffTop: 20, obstacles: [] })).toBe(null);
  });
});

describe("compound meter counts dotted-quarter beats", () => {
  test("6/8 is two beats, so it is counted in over two bars like 2/4", () => {
    expect(countInMeasures("6/8")).toBe(2);
    expect(countInWords("6/8")).toEqual(["1", "2", "Ready", "Go"]);
  });

  test("9/8 is three beats and 12/8 four, one bar each", () => {
    expect(countInWords("9/8")).toEqual(["1", "Ready", "Go"]);
    expect(countInMeasures("12/8")).toBe(1);
    expect(countInWords("12/8")).toEqual(["1", "2", "Ready", "Go"]);
  });
});
